export interface MatchPlayer {
  [steamId: string]: string; // steamId -> player name
}

export interface MatchTeam {
  id?: string;
  name: string;
  tag?: string;
  flag?: string; // Country code (e.g., "US", "EU")
  logo?: string | null; // URL to team logo
  players: MatchPlayer;
  coaches?: MatchPlayer | null;
  series_score?: number;
  matchtext?: string | null; // Override team name for single maps
}

export interface MatchConfig {
  // MatchZy expects matchid to be an integer (DB match ID).
  // We enforce number here so config builders must supply a numeric ID.
  matchid: number;
  skip_veto: true;
  min_players_to_ready?: number;
  players_per_team: number;
  team1: MatchTeam;
  team2: MatchTeam;
  num_maps: number;
  maplist: string[] | null;
  map_sides?: string[]; // e.g., ["team1_ct", "team2_ct", "knife"]
  spectators?: {
    players?: MatchPlayer;
  };
  min_spectators_to_ready?: number;
  expected_players_total?: number;
  expected_players_team1?: number;
  expected_players_team2?: number;
  wingman?: boolean;
  /**
   * Optional explicit round-limit settings passed through to MatchZy.
   * These mirror the shuffle/standard tournament settings and allow the
   * plugin to configure regulation + OT behavior from JSON in addition to
   * raw cvars.
   */
  maxRounds?: number;
  overtimeMode?: 'enabled' | 'disabled';
  overtimeSegments?: number;
  /**
   * Server ConVars to apply for this match.
   * 
   * Includes standard CS2 cvars (mp_maxrounds, mp_overtime_enable, etc.) and
   * MatchZy Enhanced v1.3.0 configuration variables:
   * 
   * - matchzy_autoready_enabled: 0 or 1
   * - matchzy_both_teams_unpause_required: 0 or 1
   * - matchzy_max_pauses_per_team: 0-999
   * - matchzy_pause_duration: 0-999 (seconds)
   * - matchzy_side_selection_enabled: 0 or 1
   * - matchzy_side_selection_time: 1-999 (seconds)
   * - matchzy_gg_enabled: 0 or 1
   * - matchzy_gg_threshold: 0.0-1.0
   * - matchzy_ffw_enabled: 0 or 1
   * - matchzy_ffw_time: 1-999 (seconds)
   * - matchzy_demo_recording_enabled: 0 or 1
   * 
   * These are automatically applied based on tournament type (see matchzyConfigService).
   */
  cvars?: {
    [key: string]: string | number;
  };
  /**
   * Frontend-only hint used by the Team view to decide whether to present
   * a manual veto flow. When true, the team veto UI is disabled and the
   * match should be treated as a fixed-map series with no veto phase.
   *
   * This flag is ignored by the MatchZy plugin itself and is purely
   * metadata carried alongside the config JSON.
   */
  vetoDisabled?: boolean;
  /**
   * MatchZy simulation mode flag.
   *
   * When true, the plugin runs the match in simulation mode (bots instead of human players).
   * This field is always sent explicitly in configs generated by this backend so that the
   * plugin’s behavior is unambiguous.
   */
  simulation?: boolean;
  /**
   * Optional simulation speed multiplier for MatchZy.
   *
   * When provided alongside `simulation: true`, this controls how fast the
   * simulated match runs (e.g. 1.0 = normal speed, 2.0 = 2x, 4.0 = 4x).
   * We pass this through as `simulation_timescale` in generated configs.
   */
  simulation_timescale?: number;
  /**
   * Optional list of Steam64 IDs that should always have in‑game admin rights
   * for this match. This is attached automatically for tournament and manual
   * matches so tournament admins can control matches on the server.
   */
  admins?: string[];
}

export interface CreateMatchInput {
  slug: string; // Unique identifier for the match (e.g., "astralis_vs_navi_27")
  /**
   * Optional manual server selection. When omitted, the backend will attempt
   * to auto-allocate an appropriate server (for manual matches) using the
   * same allocator used for tournament matches.
   */
  serverId?: string;
  config: MatchConfig;
}

export interface Match {
  id: number;
  slug: string;
  server_id: string;
  config: string; // JSON string of MatchConfig
  created_at: number;
  loaded_at?: number; // When the match was loaded on the server
  status: 'pending' | 'loaded' | 'live' | 'completed';
}

export interface MatchResponse {
  id: number;
  slug: string;
  serverId: string;
  config: MatchConfig;
  createdAt: number;
  loadedAt?: number;
  status: string;
  configUrl: string; // The URL to access this match config
  [key: string]: unknown;
}

/**
 * Match list item response - used for GET /api/matches
 */
/**
 * Player stats from match events
 */
export interface PlayerStats {
  name: string;
  steamId: string;
  kills: number;
  deaths: number;
  assists: number;
  damage: number;
  headshots: number;
}

export interface MatchMapResult {
  mapNumber: number;
  mapName?: string | null;
  team1Score: number;
  team2Score: number;
  winnerTeam?: 'team1' | 'team2' | 'none' | null;
  demoFilePath?: string | null;
  completedAt: number;
}

/**
 * Match list item response - used for GET /api/matches
 */
export interface MatchListItem {
  id: number;
  slug: string;
  round: number;
  matchNumber: number;
  [key: string]: unknown;
  team1?: {
    id: string;
    name: string;
    tag?: string;
  };
  team2?: {
    id: string;
    name: string;
    tag?: string;
  };
  winner?: {
    id: string;
    name: string;
    tag?: string;
  };
  status: string;
  serverId?: string;
  config?: Record<string, unknown>;
  demoFilePath?: string;
  createdAt: number;
  loadedAt?: number;
  completedAt?: number;
  vetoCompleted?: boolean;
  team1Players?: PlayerStats[];
  team2Players?: PlayerStats[];
  team1Score?: number;
  team2Score?: number;
  currentMap?: string | null;
  mapNumber?: number;
  mapResults?: MatchMapResult[];
  maps?: string[];
}

/**
 * Enrichable match object - BracketMatch or similar structures with optional fields
 */
export type EnrichableMatch = Record<string, unknown> & {
  team1Players?: PlayerStats[];
  team2Players?: PlayerStats[];
  team1Score?: number;
  team2Score?: number;
};

/**
 * Manual match template types (for standalone/manual matches, stored in DB)
 */
export interface ManualMatchTemplate {
  id: number;
  name: string;
  description?: string | null;
  bestOf: 'bo1' | 'bo3' | 'bo5';
  useVeto: boolean;
  startingSide: 'knife' | 'team1_ct' | 'team2_ct';
  knifeMode: 'default' | 'enabled' | 'disabled';
  playersPerTeam: number;
  maxRounds: number;
  overtimeEnabled: boolean;
  overtimeMaxRounds?: number | null;
  mapPoolId?: number | null;
  maps: string[];
  createdAt: number;
  updatedAt: number;
}

export interface ManualMatchTemplateRow {
  id: number;
  name: string;
  description?: string | null;
  best_of: string;
  use_veto: number;
  starting_side: string;
  knife_mode: string;
  players_per_team: number;
  max_rounds: number;
  overtime_enabled: number;
  overtime_max_rounds?: number | null;
  map_pool_id?: number | null;
  maps?: string | null;
  created_at: number;
  updated_at: number;
}

export interface CreateManualMatchTemplateInput {
  name: string;
  description?: string;
  bestOf: 'bo1' | 'bo3' | 'bo5';
  useVeto: boolean;
  startingSide: 'knife' | 'team1_ct' | 'team2_ct';
  knifeMode: 'default' | 'enabled' | 'disabled';
  playersPerTeam: number;
  maxRounds: number;
  overtimeEnabled: boolean;
  overtimeMaxRounds?: number | null;
  mapPoolId?: number | null;
  maps: string[];
}
